language: ruby
cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby

script: 'bundle exec rspec'

notification:
  email:
    recepients:
      - unseductable@gmail.com
    on_failure: change
    on_success: never
